Fix build against older glibc
When building on CentOS 7 with glibc 2.17 I got the following errors

  CC    auth.o
In file included from /usr/include/fcntl.h:77,
                 from platform.h:12,
                 from logger.h:20,
                 from auth.c:23:
/usr/include/bits/stat.h:106:31: error: expected identifier or ‘(’ before ‘[’ token
  106 |     __syscall_slong_t __unused[3];
      |                               ^
/usr/include/bits/stat.h:164:31: error: expected identifier or ‘(’ before ‘[’ token
  164 |     __syscall_slong_t __unused[3];
      |                               ^

  ...

  CC    endpoints.o
In file included from /usr/include/fcntl.h:77,
                 from platform.h:12,
                 from logger.h:20,
                 from endpoints.c:21:
/usr/include/bits/stat.h:106:31: error: expected identifier or ‘(’ before ‘[’ token
  106 |     __syscall_slong_t __unused[3];
      |                               ^
/usr/include/bits/stat.h:164:31: error: expected identifier or ‘(’ before ‘[’ token
  164 |     __syscall_slong_t __unused[3];
      |                               ^

This is because in mtd-priv.h we define __unused as an alias for
__attribute__((unused)) but now that we have platform.h which includes
fcntl.h, if that is included before mtd-priv.h we get the above
\\conflicts.

There may be neater ways to solve this, but the quick and simple fix is
to simply include mtd-priv.h last.

Signed-off-by: Andrew Clayton <andrew@digital-domain.net>