endpoints: Fix a missing va_end()
When running cppcheck over the code it showed the following

endpoints.c:565:13: error: va_list 'ap' was opened but not closed by va_end(). [va_end_missing]
   return -1;

Add a va_end() before the return, I'm not sure what carnage would ensue
if we didn't, but ...